### ISSUE TITLE
Add PULL_REQUEST_TEMPALTE.md

### ISSUE THREAD

**Issue by co-robo** [coala/coala-atom#78] opened 2017-10-25 16:26 UTC
Add a file named `PULL_REQUEST_TEMPLATE.md` which includes general information and guidelines for the author of Pull Request, you can see PULL_REQUEST_TEMPLATE.md of `coala` repository for reference.
label: initiatives/gci
Opened by @Monal5031 at [gitter//Monal5031](https://gitter.im//Monal5031?at=59f0bb440182fa5f4d785d0d)

**Comment by yashovardhan** [comment] 2017-10-25 19:26
duplicate of #76

**Comment by Monal5031** [comment] 2017-10-27 13:39
Please close this issue @Makman2

**Closed as completed** 2017-10-27 14:29 UTC
Labels: status/duplicate
