### ISSUE TITLE
README.md not in terms with MarkdownBear

### ISSUE THREAD

**Issue by yashovardhan** [coala/coala-atom#84] opened 2017-12-12 22:19 UTC
I ran coala in my local system, it says `The text does not comply to the set style.`
and the patch removes the whole content of the file.

this change might help close https://github.com/coala/coala-atom/issues/81

**Comment by jayvdb** [comment] 2017-12-13 04:15
Duplicate of #81

**Closed as completed by jayvdb** 2017-12-13 04:15 UTC
